"""The workspace, drawn.

Text rather than an image, on purpose. A committed PNG is a binary blob nobody
can review in a pull request and that goes stale without anyone noticing.
Mermaid renders on GitHub, in the documentation site and in most editors; it
diffs line by line; and when a slide genuinely needs a picture, it rasterises.

The edges are labelled with the environment variable that carries the binding,
because "billing talks to core-db" is the easy half. The half people get wrong
is which variable it arrives in, and that is the half a diagram can settle.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from jfastframework.workspace import Workspace

_SHAPES = {
    "postgres": ("[(", ")]"),
    "mongo": ("[(", ")]"),
    "redis": ("[(", ")]"),
    "qdrant": ("[(", ")]"),
}


def _node_id(name: str) -> str:
    """Mermaid ids cannot carry hyphens or dots without quoting."""
    return name.replace("-", "_").replace(".", "_")


def render_mermaid(workspace: Workspace) -> str:
    lines = [
        f"%% {workspace.name}: generated by `jfast workspace graph`. Do not edit.",
        "flowchart LR",
    ]

    gateway = workspace.gateway
    if gateway is not None:
        lines.append(f'    {_node_id(gateway.name)}("{gateway.name}<br/>:{gateway.port}")')

    for service in workspace.services:
        if service.is_gateway:
            continue
        node = _node_id(service.name)
        label = f"{service.name}<br/>{service.kind} :{service.port}"
        if service.language != "python":
            label += f"<br/>{service.language}"
        lines.append(f'    {node}["{label}"]')
        if gateway is not None and service.is_backend:
            lines.append(f"    {_node_id(gateway.name)} --> {node}")

    for resource in workspace.all_resources():
        open_shape, close_shape = _SHAPES.get(resource.type, ("[", "]"))
        label = f"{resource.name}<br/>{resource.type} :{resource.port}"
        lines.append(f'    {_node_id(resource.name)}{open_shape}"{label}"{close_shape}')

    for service in workspace.services:
        for binding, resource in workspace.bindings_for(service):
            variable = binding.resolved_env(resource)
            lines.append(f"    {_node_id(service.name)} -->|{variable}| {_node_id(resource.name)}")

    if len(lines) == 2:
        lines.append('    empty["nothing in this workspace yet"]')
    return "\n".join(lines) + "\n"


def render_dot(workspace: Workspace) -> str:
    lines = [
        f"// {workspace.name}: generated by `jfast workspace graph`. Do not edit.",
        "digraph workspace {",
        "  rankdir=LR;",
        '  node [fontname="Helvetica", shape=box];',
    ]

    for service in workspace.services:
        shape = "component" if service.is_gateway else "box"
        lines.append(
            f'  "{service.name}" [shape={shape}, label="{service.name}\\n'
            f'{service.kind} :{service.port}"];'
        )

    for resource in workspace.all_resources():
        lines.append(
            f'  "{resource.name}" [shape=cylinder, label="{resource.name}\\n'
            f'{resource.type} :{resource.port}"];'
        )

    gateway = workspace.gateway
    if gateway is not None:
        for service in workspace.backends:
            lines.append(f'  "{gateway.name}" -> "{service.name}";')

    for service in workspace.services:
        for binding, resource in workspace.bindings_for(service):
            variable = binding.resolved_env(resource)
            lines.append(f'  "{service.name}" -> "{resource.name}" [label="{variable}"];')

    lines.append("}")
    return "\n".join(lines) + "\n"


def render_graph(workspace: Workspace, *, output_format: str = "mermaid") -> str:
    if output_format == "mermaid":
        return render_mermaid(workspace)
    if output_format == "dot":
        return render_dot(workspace)
    raise ValueError(f"Unknown graph format {output_format!r}. Use 'mermaid' or 'dot'.")
